name: guia_de_plantas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  android: true
  ios: true
